;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack.Bite",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Harpoon",DevComment="Harpoon Attack")
+GameplayTagList=(Tag="State.Cooldown.Bite",DevComment="BiteCooldown")
+GameplayTagList=(Tag="State.Debuff.Stun",DevComment="Stun Target")

